### ISSUE TITLE
Questionnaire data: format start & end timestamps as ISO 8601

### ISSUE THREAD

**Issue by tilowestermann** [QULab/QULQuestionnaire-Android#3]
Complete date plus hours, minutes and seconds: `YYYY-MM-DDThh:mm:ssTZD` (eg 2015-03-24T08:58:30+01:00)

**Comment by ChrisKujawa** [comment]
Changed date format to 2015-03-31T10:49:58+0200 because iso is not supported 

See:
http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date
